image: node:latest

variables:
  POSTGRES_HOST: postgres
  POSTGRES_DB: massive
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: ""

services:
  - postgres:latest

test:
  stage: test
  script:
    - npm i
    - npm test
    - npm run coverage
